### ISSUE TITLE
Request for pdf access

### ISSUE THREAD

**Issue by immortal3** [LIAAD/KeywordExtractor-Datasets#4]
Thanks for the great work.
Our Experiments/Benchmarking require us to access pdfs of the datasets. I would really appreciate it if you point us to the proper way in which we can access the pdfs of the datasets. Even, pdfs of few datasets would be a great help.

**Comment by rncampos** [comment]
Thanks for using YAKE. We are glad to know that it performed well.
Unfortunately, we don't have the pdfs. From what I remember text files were the original format. In any case, I would suggest having a look at each of the papers describing the pdf or alternatively to update your framework so that it can process text files.
Good luck with your research
